[package]
name = "forest-filecoin"
version = "0.24.0"
authors = ["ChainSafe Systems <info@chainsafe.io>"]
repository = "https://github.com/ChainSafe/forest"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Rust Filecoin implementation."
exclude = [".config", ".github", ".maintain", "documentation", "scripts", "interop-tests", "go.work*"]

[lib]
name = "forest"

[workspace.dependencies]
anyhow = "1"
cid = { version = "0.11", default-features = false, features = ["std"] }
flume = "0.11"
futures = "0.3"
multihash-codetable = { version = "0.1", features = ["blake2b", "blake2s", "blake3", "sha2", "sha3", "strobe"] }
tokio = "1"

[dependencies]
ahash = "0.8"
anyhow = { workspace = true }
async-trait = "0.1"
blake2b_simd = "1"
bls-signatures = { version = "0.15", default-features = false, features = [
  "multicore",
  "blst-portable",
] } # prevent SIGINT on CI runners by using portable assembly
blstrs = { version = "0.7", features = ["portable"] }
byteorder = "1"
bytes = "1"
cbor4ii = { version = "0.2", default-features = false, features = ["use_alloc", "use_std", "serde1"] }
cfg-if = "1"
cfg-vis = "0.3"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
cid = { workspace = true }
cid_0_10 = { package = "cid", version = "0.10", default-features = false, features = ["std"] }
data-encoding = "2"
data-encoding-macro = "0.1"
derive_more = { version = "2", features = ["from", "into"] }
digest = "0.10"
displaydoc = "0.2"
either = "1"
ethereum-types = { version = "0.15", features = ["ethbloom"] }
fil_actors_shared = { version = "19", features = ["json"] }
flume = { workspace = true }
futures = { workspace = true }
fvm2 = { package = "fvm", version = "~2.10", default-features = false }
fvm3 = { package = "fvm", default-features = false, version = "~3.12", features = ["arb"] }
fvm4 = { package = "fvm", default-features = false, version = "~4.5.3", features = ["arb", "verify-signature"] }
fvm_ipld_blockstore = "0.3"
fvm_ipld_encoding = "0.5"
fvm_shared2 = { package = "fvm_shared", version = "~2.10" }
fvm_shared3 = { package = "fvm_shared", version = "~3.12", features = ["arb", "proofs"] }
fvm_shared4 = { package = "fvm_shared", version = "~4.5.3", features = ["arb", "proofs"] }
group = "0.13"
hex = { version = "0.4", features = ["serde"] }
indexmap = { version = "2", features = ["serde"] }
integer-encoding = "4.0"
ipld-core = { version = "0.4", features = ["serde", "arb"] }
itertools = "0.14"
keccak-hash = "0.11"
libsecp256k1 = "0.7"
multihash-codetable = { workspace = true }
multihash-derive = "0.9"
nom = "7"
num = "0.4"
num-bigint = "0.4"
num-derive = "0.4"
num-rational = "0.4"
num-traits = "0.2"
num_cpus = "1"
nunny = { version = "0.2", features = ["serde", "quickcheck", "schemars"] }
once_cell = "1"
parking_lot = { version = "0.12", features = ["deadlock_detection"] }
pin-project-lite = "0.2"
positioned-io = "0.3"
pretty_assertions = "1"
rand = "0.8"
rayon = "1"
regex = "1"
rlp = "0.6"
schemars = { version = "0.8", features = ["chrono", "uuid1"] }
scopeguard = "1"
semver = "1"
serde = { version = "1", default-features = false, features = ["derive"] }
serde_ipld_dagcbor = "0.6"
serde_json = { version = "1", features = ["raw_value"] }
serde_tuple = "1"
sha2 = { version = "0.10", default-features = false }
smallvec = "1"
static_assertions = "1"
strum = { version = "0.27", features = ["derive"] }
strum_macros = "0.27"
tap = "1"
tempfile = "3"
thiserror = "2"
tokio = { version = "1", features = ['full'] }
tokio-util = { version = "0.7", features = ["compat", "io-util"] }
unsigned-varint = { version = "0.8", features = ["codec"] }
uuid = { version = "1", features = ["v4", "serde"] }
zstd = "0.13"

# optional dependencies
mimalloc = { version = "0.1", optional = true, default-features = false }
paste = "1"

# This needs to be set as default. Otherwise, a regular build or test will produce
# gargantuan artifacts (around 70G for all tests). For a debugging session, you can
# temporarily comment it out.
[profile.dev]
debug = 0
split-debuginfo = "unpacked"

[profile.quick]
inherits = "release"
opt-level = 1
lto = "off"

[profile.release]
# https://doc.rust-lang.org/cargo/reference/profiles.html#strip
strip = true
# The FVM relies on catching panics. See: https://github.com/ChainSafe/forest/issues/3153
panic = "unwind"
overflow-checks = true
lto = "thin"

[profile.release-lto-fat]
inherits = "release"
lto = "fat"

# These should be refactored (probably removed) in #2984
[features]
default = []
slim = ["rustalloc"]
doctest-private = []       # see lib.rs::doctest_private
benchmark-private = []     # see lib.rs::benchmark_private
interop-tests-private = [] # see lib.rs::interop_tests_private

rustalloc = []
mimalloc = ["dep:mimalloc"]

[package.metadata.docs.rs]
# See https://docs.rs/about/metadata
rustdoc-args = ["--document-private-items"]
